#ifndef DEF_CONSTANTES
#define DEF_CONSTANTES

#define HAUTEUR 480
#define LARGEUR 640
#define NB_BITS_PAR_PIXEL 32
#define TRANSPARENCE 255
#define TAILLE_TAB_CONV 30

enum {EQUIPER, ENLEVER, OPTIMISER};

enum {INVENTAIRE, EQUIPEMENT, ETAT, GROUPE, COMPETENCES, SAUVEGARDER, CHARGER, OPTIONS, SORTIE};

enum {CASQUE, CUIRASSE, BOUCLIER, JAMBIERE};

enum {MEMBRE1, MEMBRE2, MEMBRE3, MEMBRE4};

#endif
