#ifndef DEF_CONSTANTES
#define DEF_CONSTANTES

#define MAXIMUM_SCREEN_HEIGHT 480
#define MAXIMUM_SCREEN_WIDTH 640
#define BITS_PER_PIXELS 32
#define TRANSPARENCY 255
#define STATISTICS_ARRAY_SIZE 30

#endif
